version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: talaria_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: talaria
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: talaria_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
